status = [
  "buildkite/bcc-ledger-specs",
  "ci/hydra:Bcc:bcc-ledger-specs:required",
]
timeout_sec = 7200
required_approvals = 1
block_labels = [ "WIP", "DO NOT MERGE" ]
delete_merged_branches = true
